name: Build APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download Android SDK tools
        uses: android-actions/setup-android@v2
        with:
          api-level: 33
          target: default
          build-tools: '33.0.2'

      - name: Make gradlew executable
        run: chmod +x ./gradlew || true

      - name: Build Debug APK
        run: ./gradlew assembleRelease --no-daemon
        env:
          JAVA_OPTS: -Xmx1536m

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ocultar-linha-gestos-apk
          path: app/build/outputs/apk/release/app-release.apk
